<?php
return array(
    'ADMIN_TITLE' => '后台管理系统',
    'ICON_LIST' => array(
        './Static/img/icon/1.png',
        './Static/img/icon/2.png',
        './Static/img/icon/3.png',
        './Static/img/icon/4.png',
        './Static/img/icon/5.png',
        './Static/img/icon/6.png',
        './Static/img/icon/7.png',
        './Static/img/icon/8.png',
        './Static/img/icon/9.png',
        './Static/img/icon/10.png',
        './Static/img/icon/11.png',
        './Static/img/icon/12.png',
        './Static/img/icon/13.png',
        './Static/img/icon/14.png',
        './Static/img/icon/15.png',
        './Static/img/icon/16.png',
        './Static/img/icon/17.png',
        './Static/img/icon/18.png',
        './Static/img/icon/19.png',
        './Static/img/icon/20.png',
        './Static/img/icon/21.png',
        './Static/img/icon/22.png',
        './Static/img/icon/0.ico',
        './Static/img/icon/1.ico',
        './Static/img/icon/2.ico',
        './Static/img/icon/3.ico',
        './Static/img/icon/90.ico',
    ),
);